# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ACiw9HDh_Dgq7snD_Le2GHlCCMY3Dv1s
"""

#Hasham Kiyani
#DSA Project
#SID 10910

class cms:
    # Constructor
    def __init__(self, name, atpos, phoneno, email):
        self.name = name
        self.atpos  = atpos
        self.phoneno = phoneno
        self.email = email
         
    # Function to create and append new contact   
    def accept(self, Name, atpos, phoneno, email ):
        # use  ' int(input()) ' method to take input from user
        ob = cms(Name, atpos, phoneno, email )
        ls.append(ob)
  
    # Function to display contact details     
    def display(self, ob):
            print("Name   : ", ob.name)
            print("position : ", ob.atpos)
            print("phone Number : ", ob.phoneno)
            print("Email : ", ob.email)
            print("\n")    
         
    # Search Function    
    def search(self, rn):
        for i in range(ls.__len__()):
            if(ls[i].atpos == rn):
                return i       
  
    # Delete Function                                  
    def delete(self, rn):
        i = obj.search(rn)  
        del ls[i]
  
    # Update Function   
    def update(self, rn, No):
        i = obj.search(rn)
        roll = No
        ls[i].atpos = roll;
         
    def sort(self):
        for i in ls:
            j = ls.index(i)
            #i is not the first element
            while j>0:
        #not in order
                 if ls[j-1].atpos >= ls[j].atpos:
            #swap
                    ls[j-1].atpos,ls[j].atpos = ls[j].atpos,ls[j-1].atpos
                 else:
            #in order
                       break
        j = j-1
        print("after sorting")
        for i in range(ls._len_()):    
            obj.display(ls[i])
        
        
        
# Create a list to add Contact
ls =[]
# an object of Contact class
obj = cms("", int, int, "")
s=2
while s>=2:
    print("\nOperations used, ")
    print("\n1.Accept Contacts details\n2.Display Contacts Details\n" 
        "3.Search Details of Contacts\n4.Delete Detail of Contacts" 
       "\n5.Update Contact Details\n6.sort the list\n7.Exit")
  
    ch = int(input("Enter choice:"))
    if(ch == 1):
        count=int(input("How many entries you want to add: "))
        for i in range(count):
            nam=input("Enter Name: ")
            rol=int(input("Enter Position of Number: "))
            ph=int(input("Enter Phone Number: "))
            em=input("Enter Email: ")
            obj.accept(nam,rol,ph,em)
        for j in range(ls.__len__()):
            obj.display(ls[j])
    elif(ch == 2):
        print("\n")
        print("\nList of Contacts\n")
        for i in range(ls.__len__()):    
            obj.display(ls[i])
            
    elif(ch == 3):
        print("\n Contact Found, ")
        ser=int(input("Enter position of Contact: "))
        s = obj.search(ser)
        obj.display(ls[s])
         
    elif(ch == 4):
        deli=int(input("Enter position to delete entry of Contact: "))
        obj.delete(deli)
        print(ls.__len__())
        print("List after deletion")
        for i in range(ls._len_()):    
            obj.display(ls[i])
             
    elif(ch == 5):
        upd=int(input("Enter position to update the entry of Contacts: "))
        obj.update(3, upd)
        print(ls.__len__())
        print("List after updation")
        for i in range(ls._len_()):    
            obj.display(ls[i])

    elif(ch==6):
        obj.sort()
    else:
        s=0
        print("Thank You !")